### ISSUE TITLE
feature request: non-promiscuous node_pcap session

### ISSUE THREAD

**Issue by ghost** [node-pcap/node_pcap#114]
> Note that node_pcap always opens the interface in promiscuous mode, which generally requires running as root. 

Would be really useful for us to actually avoid promiscuous mode. 

If this is not something that can be fixed in a jiffy, we'll come back and work on it down the road.

noting the relevant lines for later: https://github.com/mranney/node_pcap/blob/0a3b77ee4ebf433428a31d03468f83caba72cfba/pcap_session.cc#L186

**Comment by mildsunrise** [comment]
this would be easy to expose too
