### ISSUE TITLE
Examples of Displaying Basic Network Stats?

### ISSUE THREAD

**Issue by gOmp** [node-pcap/node_pcap#178]
{Sorry if it's not actually an issue or the wrong place to ask for it.}

Can someone please share examples of how to gather some sniffed data and show some basic net stats?
Giving an option for some basic filtering for the displayed data,
such as most used protocol/ports, most active ip and etc.

Yours truly,
A newbie in distress :)

**Comment by roccomuso** [comment]
Please refer to existing examples and doc. The module has been updated since your question.
