### ISSUE TITLE
[npm] Publish new version to npm

### ISSUE THREAD

**Issue by ide** [node-pcap/node_pcap#186]
If you are happy with the state of the repo, could you publish a new version to npm? Thanks!

**Comment by ide** [comment]
@Segflow @jmaxxz could you push 2.1.0 or 3.0.0 when you get a chance? I think it would fix issues like https://github.com/mranney/node_pcap/issues/196 where people are assuming that `npm install pcap` will work with modern Node.

**Comment by davkorss** [comment]
+1

**Comment by jscheffner** [comment]
Is there any reason to wait with publishing?

**Comment by roccomuso** [comment]
I'm waiting for a feedback from @skepticfx before publishing

**Comment by skepticfx** [comment]
@roccomuso Am not sure we have publish access to the npm `pcap` library here. Would be better to maintain a fork officially and NPM publish it from there.

**Comment by roccomuso** [comment]
Let's ask @ujjwalt to add us

**Comment by roccomuso** [comment]
@jscheffner No problem, could you give me access to the npm module too?

**Comment by jscheffner** [comment]
@roccomuso you already have

**Comment by roccomuso** [comment]
Done. aec9d802b4bfd2e87bb15d4d590fe3e36f9ebc28

Published `v2.1.0`. Tests are appreciated.

**Comment by ide** [comment]
Closing this issue since 2.1.0 is on npm, thanks.
