### ISSUE TITLE
Close session - "Segmentation fault"

### ISSUE THREAD

**Issue by Budry** [node-pcap/node_pcap#211]
Hi,
I have a problem with closing pcap session. When I call `session.close()` I get "Segmentation fault" error. Has anybody idea how to solve this problem?

Example code:

``` js
pcap_session.on('packet', function (raw_packet) {
  // ....
  pcap_session.close()
})
```

I use master version of this package and libpcap version 1.7.4

**Comment by lo1tuma** [comment]
I get the same error. The node process also exits with exit code `139`.
I’m also using node_pcap from master and node version `6.1.0`.

**Comment by Neonox31** [comment]
+1
I got same error on my side with node version `7.7.2`.

**Comment by lo1tuma** [comment]
It is already a while since I used `node-pcap` the last time, but IIRC those changes fixed the problem for me: https://github.com/lo1tuma/node_pcap/commits/seg-fault-on-close

**Comment by Neonox31** [comment]
@lo1tuma : Thanks a lot for sharing, your branch has fixed the problem for me.

**Comment by skepticfx** [comment]
@lo1tuma Mind sending a pull request? I can merge it with master

**Comment by lo1tuma** [comment]
@skepticfx Sure, here is the PR: #221. I think haven’t provided a PR right away because I did not figured out how to write a test to prevent this problem in the future.
