### ISSUE TITLE
The state of node_pcap refactoring

### ISSUE THREAD

**Issue by Subomi** [node-pcap/node_pcap#215]
this package has been undergoing refactoring for months. Please what is the state of this process and when is the next stable release? And can a new repo be opened for this, so we can contribute.

**Comment by roccomuso** [comment]
+1

**Comment by mranney** [comment]
Could somebody make a new org for this project to be transferred into? I can move the repo to that org then.

**Comment by skepticfx** [comment]
@mranney https://github.com/node-pcap 

Invited @jmaxxz to it as well (if he is still interested)

**Comment by skepticfx** [comment]
The project was originally 'libpcap bindings for node' with some awesome tcp tracking and http trace use cases as well. I think the forward should be to, purely stick to the bindings without breaking much. This should still be able to parse IP Layer, TCP Layer and UDP Layer.

Everything else should be in  another module which does just parsing of different protocols. Thus it keeps this project simple. And doesn't breaks the existing use-cases. 

Just a thought.

**Comment by skepticfx** [comment]
@mranney I guess a few projects are already referencing 'mranney/node_pcap' to install the latest version from Github. So moving to another place might break them.

**Comment by Subomi** [comment]
@skepticfx we can change the project name entirely and add some information to the README of that update.

**Comment by mranney** [comment]
I moved it over. Github should follow transparently forward/proxy references to the old name, so I think we are good there.

Can we make a pcap npm user for this as well? I think that'd be the best in case it needs to change hands again.

**Comment by skepticfx** [comment]
Sounds good @mranney 

Adding @Subomi and @roccomuso to the new org, so they can contribute to node_pcap

**Comment by roccomuso** [comment]
Hint: use feross/standard to have some standard code style.
