### ISSUE TITLE
Error: 802.11 link-layer types supported only on 802.11

### ISSUE THREAD

**Issue by zweicoder** [node-pcap/node_pcap#217]
I started an interface in monitor mode using `airmon-ng` and am trying to listen on it, but I get an error: 

```
/media/code/test/sniff/node_modules/pcap/pcap.js:49
        this.link_type = this.session.open_live(this.device_name, this.filter, this.buffer_size, this.outfile, packet_ready, this.is_monitor);
                                      ^

Error: 802.11 link-layer types supported only on 802.11
    at Error (native)
    at new PcapSession (/media/code/test/sniff/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/media/code/test/sniff/node_modules/pcap/pcap.js:123:12)
    at Object.<anonymous> (/media/code/test/sniff/sniff.js:2:24)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
```

Here's some more info:

```
$ iwconfig mon0
mon0      IEEE 802.11bgn  Mode:Monitor  Tx-Power=16 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
$ node --version
v4.2.2
```

It fails at:
`var pcapSession = pcap.createSession('mon0', 'wlan type mgt subtype probe-req');`

I have `libpcap-dev` installed just in case, running on Ubuntu 16.04, installed with `npm i git://github.com/mranney/node_pcap.git` as node-gyp was failing from the npm package.

Am I doing anything wrong?

**Comment by simepy** [comment]
I have the same problem :(

**Comment by simepy** [comment]
I fix this problem with mode monitor
With by this commands: 
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode Monitor
sudo ifconfig wlan0 up
Your interface is wlan0 or wlan1 probably
Bye :)

**Comment by mildsunrise** [comment]
this should be closed, but we can expose `link_type` option to help in problems like these

**Comment by ralphhack666** [comment]
I'm getting the same problem while running the command "wash -i wlp0s20f3"
