### ISSUE TITLE
compiling does not work in node v10.x

### ISSUE THREAD

**Issue by jupe** [node-pcap/node_pcap#242]
Looks that direct dependency `node-socketwatcher` is not compatible with node 10 which causes that this module is not either. See:
https://github.com/btrask/node-socketwatcher/issues/18

Do we have to wait that `node-socketwatcher` is updated against node 10 (recent update is 2 years old) ?.. maybe using alternative fork https://github.com/bytzdev/node-socketwatcher/commit/d252d3f8c45f565a0a48ebd155d4f9e4666798d9 could fix the issue..

**Comment by roccomuso** [comment]
Can you test again now that we merged fix?

**Comment by c-reiter** [comment]
Tested it with node v9.4.0, didn't work. Now updated node to v10.15.0 and it works. Thank you! :)

**Comment by mildsunrise** [comment]
we're no longer using socketwatcher; this can be closed
