### ISSUE TITLE
installing from npm or git does not work

### ISSUE THREAD

**Issue by Bioblaze** [node-pcap/node_pcap#244]
`0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\biobl\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/node-pcap/node_pcap.git' ]
2 info using npm@6.4.1
3 info using node@v8.11.1
4 verbose npm-session 3b510c10a02a3090
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 info lifecycle pcap@2.1.0~prepack: pcap@2.1.0
8 info lifecycle pcap@2.1.0~postpack: pcap@2.1.0
9 silly pacote git manifest for undefined@git+https://github.com/node-pcap/node_pcap.git fetched in 5829ms
10 timing stage:loadCurrentTree Completed in 6166ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 12ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule pcap@2.1.0 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/nan 729ms (from cache)
19 silly pacote range manifest for nan@^2.0.9 fetched in 751ms
20 silly resolveWithNewModule nan@2.11.1 checking installable status
21 info lifecycle socketwatcher@0.3.0~prepack: socketwatcher@0.3.0
22 info lifecycle socketwatcher@0.3.0~postpack: socketwatcher@0.3.0
23 silly pacote git manifest for socketwatcher@git+https://github.com/bytzdev/node-socketwatcher.git fetched in 3236ms
24 silly resolveWithNewModule socketwatcher@0.3.0 checking installable status
25 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3274ms
26 timing stage:loadIdealTree Completed in 3290ms
27 silly currentTree Packets@1.0.0
27 silly currentTree `-- pcap-parser@0.2.1
28 silly idealTree Packets@1.0.0
28 silly idealTree +-- nan@2.11.1
28 silly idealTree +-- pcap-parser@0.2.1
28 silly idealTree +-- pcap@2.1.0
28 silly idealTree `-- socketwatcher@0.3.0
29 silly install generateActionsToTake
30 silly diff-trees filtering actions: includeDev false includeProd true includeOpt true
31 timing stage:generateActionsToTake Completed in 12ms
32 silly diffTrees action count 3
33 silly diffTrees add nan@2.11.1
34 silly diffTrees add socketwatcher@0.3.0
35 silly diffTrees add pcap@2.1.0
36 silly decomposeActions action count 24
37 silly decomposeActions fetch nan@2.11.1
38 silly decomposeActions extract nan@2.11.1
39 silly decomposeActions preinstall nan@2.11.1
40 silly decomposeActions build nan@2.11.1
41 silly decomposeActions install nan@2.11.1
42 silly decomposeActions postinstall nan@2.11.1
43 silly decomposeActions finalize nan@2.11.1
44 silly decomposeActions refresh-package-json nan@2.11.1
45 silly decomposeActions fetch socketwatcher@0.3.0
46 silly decomposeActions extract socketwatcher@0.3.0
47 silly decomposeActions preinstall socketwatcher@0.3.0
48 silly decomposeActions build socketwatcher@0.3.0
49 silly decomposeActions install socketwatcher@0.3.0
50 silly decomposeActions postinstall socketwatcher@0.3.0
51 silly decomposeActions finalize socketwatcher@0.3.0
52 silly decomposeActions refresh-package-json socketwatcher@0.3.0
53 silly decomposeActions fetch pcap@2.1.0
54 silly decomposeActions extract pcap@2.1.0
55 silly decomposeActions preinstall pcap@2.1.0
56 silly decomposeActions build pcap@2.1.0
57 silly decomposeActions install pcap@2.1.0
58 silly decomposeActions postinstall pcap@2.1.0
59 silly decomposeActions finalize pcap@2.1.0
60 silly decomposeActions refresh-package-json pcap@2.1.0
61 silly install executeActions
62 silly doSerial global-install 24
63 verbose correctMkdir C:\Users\biobl\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
64 timing audit compress Completed in 5ms
65 info audit Submitting payload of 589bytes
66 verbose lock using C:\Users\biobl\AppData\Roaming\npm-cache\_locks\staging-0f11df8995a756ba.lock for E:\Age Of Wushu\Packets\node_modules\.staging
67 silly doParallel extract 3
68 silly extract nan@2.11.1
69 silly extract socketwatcher@0.3.0
70 silly extract pcap@2.1.0
71 silly tarball trying nan@^2.0.9 by hash: sha512-iji6k87OSXa0CcrLl9z+ZiYSuR2o+c0bGuNmXdrhTQTakxytAFsC56SArGYoiHlJlFoHSnvmhpceZJaXkVuOtA==
72 silly tarball no local data for socketwatcher@git+https://github.com/bytzdev/node-socketwatcher.git. Extracting by manifest.
73 silly tarball no local data for git+https://github.com/node-pcap/node_pcap.git. Extracting by manifest.
74 silly extract nan@^2.0.9 extracted to E:\Age Of Wushu\Packets\node_modules\.staging\nan-fde39e4b (229ms)
75 timing audit submit Completed in 969ms
76 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 968ms
77 timing audit body Completed in 1ms
78 info lifecycle socketwatcher@0.3.0~prepack: socketwatcher@0.3.0
79 info lifecycle socketwatcher@0.3.0~postpack: socketwatcher@0.3.0
80 silly extract socketwatcher@git+https://github.com/bytzdev/node-socketwatcher.git extracted to E:\Age Of Wushu\Packets\node_modules\.staging\socketwatcher-0ab33d47 (2372ms)
81 info lifecycle pcap@2.1.0~prepack: pcap@2.1.0
82 info lifecycle pcap@2.1.0~postpack: pcap@2.1.0
83 silly extract git+https://github.com/node-pcap/node_pcap.git extracted to E:\Age Of Wushu\Packets\node_modules\.staging\pcap-4bc97792 (4550ms)
84 timing action:extract Completed in 4557ms
85 silly doReverseSerial unbuild 24
86 silly doSerial remove 24
87 silly doSerial move 24
88 silly doSerial finalize 24
89 silly finalize E:\Age Of Wushu\Packets\node_modules\nan
90 silly finalize E:\Age Of Wushu\Packets\node_modules\socketwatcher
91 silly finalize E:\Age Of Wushu\Packets\node_modules\pcap
92 timing action:finalize Completed in 16ms
93 silly doParallel refresh-package-json 3
94 silly refresh-package-json E:\Age Of Wushu\Packets\node_modules\nan
95 silly refresh-package-json E:\Age Of Wushu\Packets\node_modules\socketwatcher
96 silly refresh-package-json E:\Age Of Wushu\Packets\node_modules\pcap
97 timing action:refresh-package-json Completed in 97ms
98 silly doParallel preinstall 3
99 silly preinstall nan@2.11.1
100 info lifecycle nan@2.11.1~preinstall: nan@2.11.1
101 silly preinstall socketwatcher@0.3.0
102 info lifecycle socketwatcher@0.3.0~preinstall: socketwatcher@0.3.0
103 silly preinstall pcap@2.1.0
104 info lifecycle pcap@2.1.0~preinstall: pcap@2.1.0
105 timing action:preinstall Completed in 0ms
106 silly doSerial build 24
107 silly build nan@2.11.1
108 info linkStuff nan@2.11.1
109 silly linkStuff nan@2.11.1 has E:\Age Of Wushu\Packets\node_modules as its parent node_modules
110 silly build socketwatcher@0.3.0
111 info linkStuff socketwatcher@0.3.0
112 silly linkStuff socketwatcher@0.3.0 has E:\Age Of Wushu\Packets\node_modules as its parent node_modules
113 silly build pcap@2.1.0
114 info linkStuff pcap@2.1.0
115 silly linkStuff pcap@2.1.0 has E:\Age Of Wushu\Packets\node_modules as its parent node_modules
116 timing action:build Completed in 1ms
117 silly doSerial global-link 24
118 silly doParallel update-linked 0
119 silly doSerial install 24
120 silly install nan@2.11.1
121 info lifecycle nan@2.11.1~install: nan@2.11.1
122 silly install socketwatcher@0.3.0
123 info lifecycle socketwatcher@0.3.0~install: socketwatcher@0.3.0
124 verbose lifecycle socketwatcher@0.3.0~install: unsafe-perm in lifecycle true
125 verbose lifecycle socketwatcher@0.3.0~install: PATH: C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Age Of Wushu\Packets\node_modules\socketwatcher\node_modules\.bin;E:\Age Of Wushu\Packets\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.7-Q16;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;e:\program files\graphicsmagick-1.3.26-q8;E:\Program Files\ImageMagick-7.0.6-Q16;E:\Python27\;E:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\Program Files\PuTTY\;C:\Program Files\dotnet\;E:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\doxygen\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Users\biobl\AppData\Local\atom\bin;C:\Users\biobl\AppData\Roaming\npm;E:\Program Files\Docker Toolbox;C:\Users\biobl\AppData\Local\Microsoft\WindowsApps;C:\Users\biobl\AppData\Local\Programs\Fiddler;C:\Program Files (x86)\Yarn\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WinMerge;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\php;C:\composer;E:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\IncrediBuild;E:\Program Files\TortoiseGit\bin;E:\Go\bin;C:\Users\biobl\AppData\Local\atom\bin;C:\Users\biobl\AppData\Local\Microsoft\WindowsApps;C:\Users\biobl\AppData\Local\Programs\Fiddler;C:\Users\biobl\AppData\Local\Yarn\bin;C:\Users\biobl\AppData\Roaming\Composer\vendor\bin;C:\php;C:\composer;C:\Users\biobl\AppData\Roaming\npm;E:\Program Files\heroku\bin;%GOPATH%\bin
126 verbose lifecycle socketwatcher@0.3.0~install: CWD: E:\Age Of Wushu\Packets\node_modules\socketwatcher
127 silly lifecycle socketwatcher@0.3.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
128 silly lifecycle socketwatcher@0.3.0~install: Returned: code: 0  signal: null
129 silly install pcap@2.1.0
130 info lifecycle pcap@2.1.0~install: pcap@2.1.0
131 verbose lifecycle pcap@2.1.0~install: unsafe-perm in lifecycle true
132 verbose lifecycle pcap@2.1.0~install: PATH: C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Age Of Wushu\Packets\node_modules\pcap\node_modules\.bin;E:\Age Of Wushu\Packets\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.7-Q16;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;e:\program files\graphicsmagick-1.3.26-q8;E:\Program Files\ImageMagick-7.0.6-Q16;E:\Python27\;E:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\Program Files\PuTTY\;C:\Program Files\dotnet\;E:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\doxygen\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Users\biobl\AppData\Local\atom\bin;C:\Users\biobl\AppData\Roaming\npm;E:\Program Files\Docker Toolbox;C:\Users\biobl\AppData\Local\Microsoft\WindowsApps;C:\Users\biobl\AppData\Local\Programs\Fiddler;C:\Program Files (x86)\Yarn\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WinMerge;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\php;C:\composer;E:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\IncrediBuild;E:\Program Files\TortoiseGit\bin;E:\Go\bin;C:\Users\biobl\AppData\Local\atom\bin;C:\Users\biobl\AppData\Local\Microsoft\WindowsApps;C:\Users\biobl\AppData\Local\Programs\Fiddler;C:\Users\biobl\AppData\Local\Yarn\bin;C:\Users\biobl\AppData\Roaming\Composer\vendor\bin;C:\php;C:\composer;C:\Users\biobl\AppData\Roaming\npm;E:\Program Files\heroku\bin;%GOPATH%\bin
133 verbose lifecycle pcap@2.1.0~install: CWD: E:\Age Of Wushu\Packets\node_modules\pcap
134 silly lifecycle pcap@2.1.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
135 silly lifecycle pcap@2.1.0~install: Returned: code: 1  signal: null
136 info lifecycle pcap@2.1.0~install: Failed to exec install script
137 timing action:install Completed in 9828ms
138 verbose unlock done using C:\Users\biobl\AppData\Roaming\npm-cache\_locks\staging-0f11df8995a756ba.lock for E:\Age Of Wushu\Packets\node_modules\.staging
139 timing stage:rollbackFailedOptional Completed in 160ms
140 timing stage:runTopLevelLifecycles Completed in 24227ms
141 silly saveTree Packets@1.0.0
141 silly saveTree +-- pcap-parser@0.2.1
141 silly saveTree `-- pcap@2.1.0
141 silly saveTree   +-- nan@2.11.1
141 silly saveTree   `-- socketwatcher@0.3.0
142 warn Packets@1.0.0 No description
143 warn Packets@1.0.0 No repository field.
144 verbose stack Error: pcap@2.1.0 install: `node-gyp rebuild`
144 verbose stack Exit status 1
144 verbose stack     at EventEmitter.<anonymous> (C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
144 verbose stack     at emitTwo (events.js:126:13)
144 verbose stack     at EventEmitter.emit (events.js:214:7)
144 verbose stack     at ChildProcess.<anonymous> (C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
144 verbose stack     at emitTwo (events.js:126:13)
144 verbose stack     at ChildProcess.emit (events.js:214:7)
144 verbose stack     at maybeClose (internal/child_process.js:925:16)
144 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
145 verbose pkgid pcap@2.1.0
146 verbose cwd E:\Age Of Wushu\Packets
147 verbose Windows_NT 10.0.17134
148 verbose argv "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\biobl\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/node-pcap/node_pcap.git"
149 verbose node v8.11.1
150 verbose npm  v6.4.1
151 error code ELIFECYCLE
152 error errno 1
153 error pcap@2.1.0 install: `node-gyp rebuild`
153 error Exit status 1
154 error Failed at the pcap@2.1.0 install script.
154 error This is probably not a problem with npm. There is likely additional logging output above.
155 verbose exit [ 1, true ]
`

From Console:
`E:\Age Of Wushu\Packets>npm install https://github.com/node-pcap/node_pcap.git

> socketwatcher@0.3.0 install E:\Age Of Wushu\Packets\node_modules\socketwatcher
> node-gyp rebuild

E:\Age Of Wushu\Packets\node_modules\socketwatcher>if not defined npm_config_node_gyp (node "C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  socket_watcher.cpp
  win_delay_load_hook.cc
e:\age of wushu\packets\node_modules\socketwatcher\socket_watcher.cpp(77): warning C4996: 'Nan::MakeCallback': was decl
ared deprecated [E:\Age Of Wushu\Packets\node_modules\socketwatcher\build\socketwatcher.vcxproj]
  e:\age of wushu\packets\node_modules\nan\nan.h(958): note: see declaration of 'Nan::MakeCallback'
     Creating library E:\Age Of Wushu\Packets\node_modules\socketwatcher\build\Release\socketwatcher.lib and object E:\
  Age Of Wushu\Packets\node_modules\socketwatcher\build\Release\socketwatcher.exp
  Generating code
  Finished generating code
  socketwatcher.vcxproj -> E:\Age Of Wushu\Packets\node_modules\socketwatcher\build\Release\\socketwatcher.node

> pcap@2.1.0 install E:\Age Of Wushu\Packets\node_modules\pcap
> node-gyp rebuild

E:\Age Of Wushu\Packets\node_modules\pcap>if not defined npm_config_node_gyp (node "C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcap_binding.cc
  pcap_session.cc
  win_delay_load_hook.cc
e:\age of wushu\packets\node_modules\pcap\pcap_session.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h
': No such file or directory [E:\Age Of Wushu\Packets\node_modules\pcap\build\pcap_binding.vcxproj]
e:\age of wushu\packets\node_modules\pcap\pcap_binding.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h
': No such file or directory [E:\Age Of Wushu\Packets\node_modules\pcap\build\pcap_binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `E:\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\biobl\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\biobl\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Age Of Wushu\Packets\node_modules\pcap
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN Packets@1.0.0 No description
npm WARN Packets@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\biobl\AppData\Roaming\npm-cache\_logs\2018-10-23T18_18_48_866Z-debug.log`

**Comment by roccomuso** [comment]
I'm not able to run and debug it on Windows.
Could be a known issue

**Comment by mildsunrise** [comment]
windows is definitely not supported, see https://github.com/node-pcap/node_pcap/issues/249#issuecomment-586201286. this should be closed
