### ISSUE TITLE
  Error: Don't know how to process TCP option 112

### ISSUE THREAD

**Issue by digitalrinaldo** [node-pcap/node_pcap#245]
throw new Error("Don't know how to process TCP option " + raw_packet[offset]);             ^  Error: Don't know how to process TCP option 112

Program actually exists with the above rather than indicating an error and continuing. I did not see this error in any of the issues or on the web.

**Comment by jscheffner** [comment]
Not for this specific option but for unknown options in general: #240

**Comment by jschulenklopper** [comment]
So, this issue can be closed as duplicate (or sub case) of #240, I'd say.
