### ISSUE TITLE
NPM install problem

### ISSUE THREAD

**Issue by CJLees01** [node-pcap/node_pcap#70]
I'm getting an error whenever I try to use npm to install this. Any suggestions please?

Node v0.10.10
Ubuntu 12.10 (but I have exactly the same error on CentOS 6.2)

chris@chris-desktop:~/Node/Parser$ npm install pcap
npm http GET https://registry.npmjs.org/pcap
npm http 304 https://registry.npmjs.org/pcap
npm http GET https://registry.npmjs.org/socketwatcher
npm http 304 https://registry.npmjs.org/socketwatcher

> socketwatcher@0.2.0 install /home/chris/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild
> make: Entering directory `/home/chris/node_modules/pcap/node_modules/socketwatcher/build'
>   CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
>   SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
>   SOLINK_MODULE(target) Release/obj.target/socketwatcher.node: Finished
>   COPY Release/socketwatcher.node
> make: Leaving directory`/home/chris/node_modules/pcap/node_modules/socketwatcher/build'
> pcap@1.0.0 install /home/chris/node_modules/pcap
> node-gyp rebuild
> make: Entering directory `/home/chris/node_modules/pcap/build'
>   CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
>   CXX(target) Release/obj.target/pcap_binding/pcap_session.o
> ../pcap_session.cc: In static member function ‘static void PcapSession::PacketReady(u_char*, const pcap_pkthdr*, const u_char*)’:
> ../pcap_session.cc:72:50: error: ‘memcpy’ was not declared in this scope
> ../pcap_session.cc: In static member function ‘static v8::Handle<v8::Value> PcapSession::Open(bool, const v8::Arguments&)’:
> ../pcap_session.cc:202:50: error: ‘strlen’ was not declared in this scope
> make: *** [Release/obj.target/pcap_binding/pcap_session.o] Error 1
> make: Leaving directory`/home/chris/node_modules/pcap/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
> gyp ERR! System Linux 3.5.0-39-generic
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/chris/node_modules/pcap
> gyp ERR! node -v v0.10.10
> gyp ERR! node-gyp -v v0.9.6
> gyp ERR! not ok 
> npm ERR! weird error 1
> npm ERR! not ok code 0

**Comment by soua-hamza** [comment]
i have the same , not installing with NPM
