### ISSUE TITLE
Can't find pcap.h

### ISSUE THREAD

**Issue by Chris2011** [node-pcap/node_pcap#95]
Hi,

I saw this guide: https://github.com/TooTallNate/node-gyp/wiki/Visual-Studio-2010-Setup
and installed VS2012 express, after this I tried the SDK. After some errors, I uninstalled all redistributable vs2008 and vs2010 and then all is ok with the SDK. No I tried npm install -g pcap and I got this error:

  pcap_binding.cc
  pcap_session.cc
..\pcap_binding.cc(5): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\ChrisLE\AppData\Roaming\npm\node_modules\pcap\build\pcap_binding.vcxproj]
..\pcap_session.cc(4): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\ChrisLE\AppData\Roaming\npm\node_modules\pcap\build\pcap_binding.vcxproj]

I use Windows 7 64, installed WinPCAP. Did I forget smth?

Cheers,

Chris

**Comment by ericrange** [comment]
+1 cant install on windows!!

**Comment by ujjwalt** [comment]
Guys can you try once again after the major refactor

**Comment by skepticfx** [comment]
@ujjwalt Not sure whether the refactor catered for Windows support. I wouldn't be surprised if it still doesn't work.

**Comment by mranney** [comment]
I didn't do much to the C++ side, so I'd be surprised if it suddenly worked.

I don't run Windows, but it would be great if somebody who did could help properly windows-ify the installation process.

**Comment by skepticfx** [comment]
@mranney Pcap on Windows w.r.t V8 Binding requires a little bit more research.

**Comment by Domiii** [comment]
I have not got it to work on Windows yet, but there are two big pre-reqs to getting it working:

1. Get the [WinPcap Developer Pack](https://www.winpcap.org/devel.htm)
2. Locate MSBuild's global configuration directory in `%LOCALAPPDATA%\Microsoft\MSBuild`
3. Add WinPcap Developer Pack `include` and `lib` directories to MSBuild's global configuration. 

I have not yet succeeded in achieving this really essential setup. I assumed, it should work by adding something like this to the global configuration file (but it did not):

    <ItemGroup>
        <Compile Include="the_dir_here">
    </ItemGroup>

**Comment by ujjwalt** [comment]
I request anyone here with any windows expertise to resolve this. I have none and therefore am unable to help out with windows

**Comment by MusicalCreeper01** [comment]
See http://stackoverflow.com/questions/2676417/how-do-include-paths-work-in-visual-studio/35591563#35591563 for information on adding the dev pack's include and lib folders to the global includes for windows :)

**Comment by Chris2011** [comment]
I will Test it later

**Comment by MusicalCreeper01** [comment]
Btw It does fix the pcsp dependencies, but shows other missing dependencies/headers that are not available for Windows.

On Jan 29, 2017, at 12:39 AM, Chrizzly <notifications@github.com<mailto:notifications@github.com>> wrote:


I will Test it later

-

**Comment by Fivezero05** [comment]
The solution  : 

Create folder
.....\Pcap.Net\PcapDotNet\3rdParty

In 3rdParty folder you put everything from the developerkit  ( https://www.winpcap.org/devel.htm )

when you are done you should now find pcap.h in :  
....\Pcap.Net\PcapDotNet\3rdParty\WpdPack\Include\

Now you can compile 
....\Pcap.Net\PcapDotNet\src\PcapDotNet.sln


In case this is explained somewhere else: apologies.

**Comment by nankezhou** [comment]
I already solved it ，please see，
http://gotovpn.blogspot.com/2018/02/solve-most-important-issues-for-nss.html
THANK YOU!

**Comment by koooge** [comment]
I got same issue when I installed **node-dash-button**

```
PS C:\Users\koooo\Documents\dasher> npm i node-dash-button

> pcap@2.0.0 install C:\Users\koooo\Documents\dasher\node_modules\pcap
> node-gyp rebuild


C:\Users\koooo\Documents\dasher\node_modules\pcap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcap_binding.cc
  pcap_session.cc
  win_delay_load_hook.cc
..\pcap_binding.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\koooo\Documents\dasher\node_modules\pcap\build\pcap_binding.vcxproj]
..\pcap_session.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\koooo\Documents\dasher\node_modules\pcap\build\pcap_binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\koooo\Documents\dasher\node_modules\pcap
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koooo\AppData\Roaming\npm-cache\_logs\2018-05-19T12_13_16_898Z-debug.log
```

**Comment by bariskayar** [comment]
extract WpdPack
copy Include and Lib folders to  node_pcap folder.
add Include and Lib folders to include_dirs var in node_pcap\binding.gyp like below.
and try to build again (node-gyp configure build)

{
  "targets": [
    {
      "target_name": "pcap_binding",
      "sources": [ "pcap_binding.cc", "pcap_session.cc" ],
      "include_dirs": [
		**"Include",
		"Lib",**
        "<!(node -e \"require('nan')\")"
      ],
      "link_settings": {
          "libraries": [
              "-lpcap"
          ]
      }
    }
  ]
}

**Comment by Chris2011** [comment]
I will try to use the cap package, it seems more up to date. Just FYI.
